stages:
  - lint
  - test


Linting:
  stage: lint
  image: python:3.8
  before_script:
    - pip install wemake-python-styleguide=="0.14.1"
  script:
    - flake8 --config=setup.cfg ./src/app/core/hw_10_api.py
    - flake8 --config=setup.cfg ./src/app/core/hw_10_calculator.py
    - flake8 --config=setup.cfg ./src/app/core/hw_10_model.py
  allow_failure: true

Test:
  stage: test
  image: python:3.8
  before_script:
    - pip install pytest
    - pip install poetry
    - poetry install --no-root
  script:
    - export PYTHONPATH="$PWD/src:$PYTHONPATH"
    - pytest tests/core/app/calculator/
  allow_failure: true